export interface CarInterface {
    carId?: number,
    make: string,
    model: string,
    fourWheelDrive: boolean,
    userId?: number
}

//every car needs a registered make, model, and isFourWheelDrive
//carId and userId are optional - we don't supply these values if we're inserting a car
    //carId is autogenerated. userId will be supplied by the saved logged in user data